### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Blueforcer** [schmic/Loupedeck-HomeAssistant#10]
Maybe im missing something, but how this plugin is working? Is there any tutorial?
Im using v0.7 and only have one single action wich i can use.
![image](https://github.com/schmic/Loupedeck-HomeAssistant/assets/31169771/5a2a10f3-76ae-442d-8722-11120222031e)

**Comment by schmic** [comment]
There is an explanation on how to configure the plugin on this repositories [README.md](https://github.com/schmic/Loupedeck-HomeAssistant/blob/main/README.md)

If you did do that correctly your entities show up and you can use them in your Loupedeck. Otherwise check the `HA.log` of the plugin and/or attach it here. You can find it at `%LocalAppData%\Loupedeck\Logs`
